### ISSUE TITLE
Using a button is not correct for that context

### ISSUE THREAD

**Issue by shadeed** [kholoud840/NoonPost-repo#5]
<img width="248" alt="screen shot 2018-03-24 at 8 17 17 pm" src="https://user-images.githubusercontent.com/8038659/37866786-6434b3d6-2fa0-11e8-96eb-95de5f45f10d.png">

Since this will navigate to a new page, this should be a link.

**Comment by shadeed** [comment]
@kholoud840  Also the font size is too small, 16px is good (I think)

**Comment by kholoud840** [comment]
Got it!
I just followed the design measurements for the font size.
